import Head from "next/head";
import ConvertionComponent from "../components/convertionComponent";
import CurrencyExchangeComponent from "../components/currencyExchangeComponent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Let's create a currency exchange house app!</h1>
        <ConvertionComponent />
        <CurrencyExchangeComponent />
      </main>
    </div>
  );
}
